### ISSUE TITLE
Clean up repo for next milestone

### ISSUE THREAD

**Issue by sshine** [Sword-Smith/Sword#28]
This is a short brainstorm on issues that we can focus on in 2021.

- [x] Remove all references to "Dagger" and "daggerc".
- [ ] Fix module imports. (This helps to locate dead code.)
- [ ] Remove dead code.
- [ ] Clean up package.yaml.
- [ ] Remove broken tests in cases where semantics have changed.
- [ ] Set up Continuous Integration
    - [ ] Unit tests (easy to set up; current tests don't give us much)
    - [ ] Integration tests (requires geth_tools or similar gives deterministic results)
